### ISSUE TITLE
bug with multiple devices on I2C

### ISSUE THREAD

**Issue by DTLamb** [deskwizard/Arduino_DAC_ADC_libraries#1]
Trying to access 2 TI DAC 7678 on the same I2C bus.  Only one address is accessed.  I think (not much of a programmer...) the issue is the address variable (adc7678_address) is declared as Class variable and needs to be Member variable.

**Comment by deskwizard** [comment]
Hi,
Sorry about the delay. I will try to look into it when I have a bit of time.
I haven't touch that in ages. I will come back to you.

**Comment by deskwizard** [comment]
Hi,
I'm sorry to tell you that I don't have any more of those chips on hand, hence I will not be able to test anything. I'm not much of a programmer either but your explanation sounds right to me...

EDIT: Found them, will push when fixed

**Comment by deskwizard** [comment]
Fix pushed. Thanks for the feedback!
